name: Docker Image CI/CD

on:
  push:
    branches:
      - main   # Trigger on pushes to the main branch (modify as needed)
  pull_request:
    branches:
      - main   # Trigger on pull requests targeting the main branch

jobs:
  build-and-push-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (Optional: Add your credentials as secrets in GitHub)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the frontend Docker image
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rapidfort-frontend:latest

    # Build and push the backend Docker image
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rapidfort-backend:latest
